key_in_json = {
    # "nose": 0,
    # "left-eye": 1,
    # "right-eye": 2,
    # "left-ear": 3,
    # "right-ear": 4,
    "left-shoulder": 5,
    "right-shoulder": 6,
    "left-elbow": 7,
    "right-elbow": 8,
    "left-wrist": 9,
    "right-wrist": 10,
    "left-hip": 11,
    "right-hip": 12,
    "left-knee": 13,
    "right-knee": 14,
    "left-ankle": 15,
    "right-ankle": 16,
}
key_in_ref = {
    # "nose": 0,
    # "left-eye": 1,
    # "right-eye": 2,
    # "left-ear": 3,
    # "right-ear": 4,
    "left-shoulder": 5,
    "right-shoulder": 6,
    "left-elbow": 7,
    "right-elbow": 8,
    "left-hip": 9,
    "right-hip": 10,
    "left-knee": 11,
    "right-knee": 12,
    "left-ankle": 13,
    "right-ankle": 14,
    "left-wrist": 62,
    "right-wrist": 41,
}
